
version: 2
jobs:
  build: #use the name of the root directory
    working_directory: ~/circleci-demo-python-django
    
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout #checkout source code to working directory, meaning that it makes a copy of it
      - run:
          command: | # use venv to install dependencies
            python3 -m venv venv
            . venv/bin/activate
            pip install -r circleci-demo-python-django/requirements.txt
